### ISSUE TITLE
有一点不流畅

### ISSUE THREAD

**Issue by lzc1022** [mayan29/TreeTableView#1]
![8ff67f07-e8f9-4eff-99bd-06d41a980300](https://user-images.githubusercontent.com/9947322/41580138-59e92770-73cc-11e8-83ce-c1788be86a21.png)
点击第一个父节点，下面有明显的不流畅

**Comment by mayan29** [comment]
使用 iPhone 6 和 iPhone 6s 测试，均未发现不流畅。

猜测可能出现不流畅的原因：使用 insertRowsAtIndexPaths:withRowAnimation: 方法可能在 cell 过多的情况下出现卡顿。现在已经在 MYTreeTableViewController.h 添加 isShowExpandAnimation 字段，可以设置取消展开/折叠动画，没有动画的情况下，流畅度大大提高。

**Comment by chao-29** [comment]
第一个demo怎么没了
