### ISSUE TITLE
你好，使用单选的选择后还是能选择多个啊

### ISSUE THREAD

**Issue by meliuxudong** [mayan29/TreeTableView#3]
是我操作有问题还是怎么的。

**Comment by meliuxudong** [comment]
嘿嘿，我在checkButtonClickBlock的回调里最上面加了句
if (wself.isSingleCheck) {
            if (item.checkState != MYTreeItemChecked) [wself.manager checkAllItem:NO];
        }
就可以了。

**Comment by mayan29** [comment]
感谢反馈！最近有些忙，过一段时间再修改完善！

**Comment by mayan29** [comment]
不好意思，过了这么久才修复，现在已经这个 bug 已经解决。

**Comment by wanyijun** [comment]
没改好 现在单选还是可以多选

**Comment by houjiaming** [comment]
> 嘿嘿，我在checkButtonClickBlock的回调里最上面加了句
> if (wself.isSingleCheck) {
> if (item.checkState != MYTreeItemChecked) [wself.manager checkAllItem:NO];
> }
> 就可以了。

完美解决了单选问题

**Comment by mayan29** [comment]
bug 已修复
